//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_static!(CBAdvertisementDataLocalNameKey: &'static NSString);

extern_static!(CBAdvertisementDataTxPowerLevelKey: &'static NSString);

extern_static!(CBAdvertisementDataServiceUUIDsKey: &'static NSString);

extern_static!(CBAdvertisementDataServiceDataKey: &'static NSString);

extern_static!(CBAdvertisementDataManufacturerDataKey: &'static NSString);

extern_static!(CBAdvertisementDataOverflowServiceUUIDsKey: &'static NSString);

extern_static!(CBAdvertisementDataIsConnectable: &'static NSString);

extern_static!(CBAdvertisementDataSolicitedServiceUUIDsKey: &'static NSString);
