//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBATTRequest")]
    pub struct CBATTRequest;

    #[cfg(feature = "CoreBluetooth_CBATTRequest")]
    unsafe impl ClassType for CBATTRequest {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBATTRequest")]
unsafe impl NSObjectProtocol for CBATTRequest {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBATTRequest")]
    unsafe impl CBATTRequest {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "CoreBluetooth_CBCentral")]
        #[method_id(@__retain_semantics Other central)]
        pub unsafe fn central(&self) -> Id<CBCentral>;

        #[cfg(feature = "CoreBluetooth_CBCharacteristic")]
        #[method_id(@__retain_semantics Other characteristic)]
        pub unsafe fn characteristic(&self) -> Id<CBCharacteristic>;

        #[method(offset)]
        pub unsafe fn offset(&self) -> NSUInteger;

        #[cfg(feature = "Foundation_NSData")]
        #[method_id(@__retain_semantics Other value)]
        pub unsafe fn value(&self) -> Option<Id<NSData>>;

        #[cfg(feature = "Foundation_NSData")]
        #[method(setValue:)]
        pub unsafe fn setValue(&self, value: Option<&NSData>);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBATTRequest")]
    unsafe impl CBATTRequest {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
