//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBAttribute")]
    pub struct CBAttribute;

    #[cfg(feature = "CoreBluetooth_CBAttribute")]
    unsafe impl ClassType for CBAttribute {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBAttribute")]
unsafe impl NSObjectProtocol for CBAttribute {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBAttribute")]
    unsafe impl CBAttribute {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "CoreBluetooth_CBUUID")]
        #[method_id(@__retain_semantics Other UUID)]
        pub unsafe fn UUID(&self) -> Id<CBUUID>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBAttribute")]
    unsafe impl CBAttribute {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
