//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBCentral")]
    pub struct CBCentral;

    #[cfg(feature = "CoreBluetooth_CBCentral")]
    unsafe impl ClassType for CBCentral {
        #[inherits(NSObject)]
        type Super = CBPeer;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBCentral")]
unsafe impl NSCopying for CBCentral {}

#[cfg(feature = "CoreBluetooth_CBCentral")]
unsafe impl NSObjectProtocol for CBCentral {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBCentral")]
    unsafe impl CBCentral {
        #[method(maximumUpdateValueLength)]
        pub unsafe fn maximumUpdateValueLength(&self) -> NSUInteger;
    }
);

extern_methods!(
    /// Methods declared on superclass `CBPeer`
    #[cfg(feature = "CoreBluetooth_CBCentral")]
    unsafe impl CBCentral {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBCentral")]
    unsafe impl CBCentral {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
