//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_static!(CBCentralManagerOptionShowPowerAlertKey: &'static NSString);

extern_static!(CBCentralManagerOptionRestoreIdentifierKey: &'static NSString);

extern_static!(CBCentralManagerOptionDeviceAccessForMedia: &'static NSString);

extern_static!(CBCentralManagerScanOptionAllowDuplicatesKey: &'static NSString);

extern_static!(CBCentralManagerScanOptionSolicitedServiceUUIDsKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionNotifyOnConnectionKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionNotifyOnDisconnectionKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionNotifyOnNotificationKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionStartDelayKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionEnableTransportBridgingKey: &'static NSString);

extern_static!(CBConnectPeripheralOptionRequiresANCS: &'static NSString);

extern_static!(CBCentralManagerRestoredStatePeripheralsKey: &'static NSString);

extern_static!(CBCentralManagerRestoredStateScanServicesKey: &'static NSString);

extern_static!(CBCentralManagerRestoredStateScanOptionsKey: &'static NSString);

typed_enum!(
    pub type CBConnectionEventMatchingOption = NSString;
);

extern_static!(CBConnectionEventMatchingOptionServiceUUIDs: &'static CBConnectionEventMatchingOption);

extern_static!(CBConnectionEventMatchingOptionPeripheralUUIDs: &'static CBConnectionEventMatchingOption);

extern_static!(CBConnectPeripheralOptionEnableAutoReconnect: &'static NSString);
