//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_static!(CBErrorDomain: &'static NSString);

ns_enum!(
    #[underlying(NSInteger)]
    pub enum CBError {
        CBErrorUnknown = 0,
        CBErrorInvalidParameters = 1,
        CBErrorInvalidHandle = 2,
        CBErrorNotConnected = 3,
        CBErrorOutOfSpace = 4,
        CBErrorOperationCancelled = 5,
        CBErrorConnectionTimeout = 6,
        CBErrorPeripheralDisconnected = 7,
        CBErrorUUIDNotAllowed = 8,
        CBErrorAlreadyAdvertising = 9,
        CBErrorConnectionFailed = 10,
        CBErrorConnectionLimitReached = 11,
        #[deprecated = "Use CBErrorUnknownDevice instead"]
        CBErrorUnkownDevice = 12,
        CBErrorUnknownDevice = 12,
        CBErrorOperationNotSupported = 13,
        CBErrorPeerRemovedPairingInformation = 14,
        CBErrorEncryptionTimedOut = 15,
        CBErrorTooManyLEPairedDevices = 16,
        CBErrorLeGattExceededBackgroundNotificationLimit = 17,
        CBErrorLeGattNearBackgroundNotificationLimit = 18,
    }
);

extern_static!(CBATTErrorDomain: &'static NSString);

ns_enum!(
    #[underlying(NSInteger)]
    pub enum CBATTError {
        CBATTErrorSuccess = 0x00,
        CBATTErrorInvalidHandle = 0x01,
        CBATTErrorReadNotPermitted = 0x02,
        CBATTErrorWriteNotPermitted = 0x03,
        CBATTErrorInvalidPdu = 0x04,
        CBATTErrorInsufficientAuthentication = 0x05,
        CBATTErrorRequestNotSupported = 0x06,
        CBATTErrorInvalidOffset = 0x07,
        CBATTErrorInsufficientAuthorization = 0x08,
        CBATTErrorPrepareQueueFull = 0x09,
        CBATTErrorAttributeNotFound = 0x0A,
        CBATTErrorAttributeNotLong = 0x0B,
        CBATTErrorInsufficientEncryptionKeySize = 0x0C,
        CBATTErrorInvalidAttributeValueLength = 0x0D,
        CBATTErrorUnlikelyError = 0x0E,
        CBATTErrorInsufficientEncryption = 0x0F,
        CBATTErrorUnsupportedGroupType = 0x10,
        CBATTErrorInsufficientResources = 0x11,
    }
);
