//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

pub type CBL2CAPPSM = u16;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBL2CAPChannel")]
    pub struct CBL2CAPChannel;

    #[cfg(feature = "CoreBluetooth_CBL2CAPChannel")]
    unsafe impl ClassType for CBL2CAPChannel {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBL2CAPChannel")]
unsafe impl NSObjectProtocol for CBL2CAPChannel {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBL2CAPChannel")]
    unsafe impl CBL2CAPChannel {
        #[cfg(feature = "CoreBluetooth_CBPeer")]
        #[method_id(@__retain_semantics Other peer)]
        pub unsafe fn peer(&self) -> Option<Id<CBPeer>>;

        #[cfg(feature = "Foundation_NSInputStream")]
        #[method_id(@__retain_semantics Other inputStream)]
        pub unsafe fn inputStream(&self) -> Option<Id<NSInputStream>>;

        #[cfg(feature = "Foundation_NSOutputStream")]
        #[method_id(@__retain_semantics Other outputStream)]
        pub unsafe fn outputStream(&self) -> Option<Id<NSOutputStream>>;

        #[method(PSM)]
        pub unsafe fn PSM(&self) -> CBL2CAPPSM;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBL2CAPChannel")]
    unsafe impl CBL2CAPChannel {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
