//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

ns_enum!(
    #[underlying(NSInteger)]
    pub enum CBManagerState {
        CBManagerStateUnknown = 0,
        CBManagerStateResetting = 1,
        CBManagerStateUnsupported = 2,
        CBManagerStateUnauthorized = 3,
        CBManagerStatePoweredOff = 4,
        CBManagerStatePoweredOn = 5,
    }
);

ns_enum!(
    #[underlying(NSInteger)]
    pub enum CBManagerAuthorization {
        CBManagerAuthorizationNotDetermined = 0,
        CBManagerAuthorizationRestricted = 1,
        CBManagerAuthorizationDenied = 2,
        CBManagerAuthorizationAllowedAlways = 3,
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBManager")]
    pub struct CBManager;

    #[cfg(feature = "CoreBluetooth_CBManager")]
    unsafe impl ClassType for CBManager {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBManager")]
unsafe impl NSObjectProtocol for CBManager {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBManager")]
    unsafe impl CBManager {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method(state)]
        pub unsafe fn state(&self) -> CBManagerState;

        #[deprecated]
        #[method(authorization)]
        pub unsafe fn authorization(&self) -> CBManagerAuthorization;

        #[method(authorization)]
        pub unsafe fn authorization_class() -> CBManagerAuthorization;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBManager")]
    unsafe impl CBManager {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
