//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_static!(CBPeripheralManagerOptionShowPowerAlertKey: &'static NSString);

extern_static!(CBPeripheralManagerOptionRestoreIdentifierKey: &'static NSString);

extern_static!(CBPeripheralManagerRestoredStateServicesKey: &'static NSString);

extern_static!(CBPeripheralManagerRestoredStateAdvertisementDataKey: &'static NSString);
