//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBPeer")]
    pub struct CBPeer;

    #[cfg(feature = "CoreBluetooth_CBPeer")]
    unsafe impl ClassType for CBPeer {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBPeer")]
unsafe impl NSCopying for CBPeer {}

#[cfg(feature = "CoreBluetooth_CBPeer")]
unsafe impl NSObjectProtocol for CBPeer {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBPeer")]
    unsafe impl CBPeer {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[cfg(feature = "Foundation_NSUUID")]
        #[method_id(@__retain_semantics Other identifier)]
        pub unsafe fn identifier(&self) -> Id<NSUUID>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBPeer")]
    unsafe impl CBPeer {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
