//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBService")]
    pub struct CBService;

    #[cfg(feature = "CoreBluetooth_CBService")]
    unsafe impl ClassType for CBService {
        #[inherits(NSObject)]
        type Super = CBAttribute;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBService")]
unsafe impl NSObjectProtocol for CBService {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBService")]
    unsafe impl CBService {
        #[cfg(feature = "CoreBluetooth_CBPeripheral")]
        #[method_id(@__retain_semantics Other peripheral)]
        pub unsafe fn peripheral(&self) -> Option<Id<CBPeripheral>>;

        #[method(isPrimary)]
        pub unsafe fn isPrimary(&self) -> bool;

        #[cfg(feature = "Foundation_NSArray")]
        #[method_id(@__retain_semantics Other includedServices)]
        pub unsafe fn includedServices(&self) -> Option<Id<NSArray<CBService>>>;

        #[cfg(all(
            feature = "CoreBluetooth_CBCharacteristic",
            feature = "Foundation_NSArray"
        ))]
        #[method_id(@__retain_semantics Other characteristics)]
        pub unsafe fn characteristics(&self) -> Option<Id<NSArray<CBCharacteristic>>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `CBAttribute`
    #[cfg(feature = "CoreBluetooth_CBService")]
    unsafe impl CBService {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBService")]
    unsafe impl CBService {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBMutableService")]
    pub struct CBMutableService;

    #[cfg(feature = "CoreBluetooth_CBMutableService")]
    unsafe impl ClassType for CBMutableService {
        #[inherits(CBAttribute, NSObject)]
        type Super = CBService;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBMutableService")]
unsafe impl NSObjectProtocol for CBMutableService {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBMutableService")]
    unsafe impl CBMutableService {
        #[cfg(feature = "Foundation_NSArray")]
        #[method_id(@__retain_semantics Other includedServices)]
        pub unsafe fn includedServices(&self) -> Option<Id<NSArray<CBService>>>;

        #[cfg(feature = "Foundation_NSArray")]
        #[method(setIncludedServices:)]
        pub unsafe fn setIncludedServices(&self, included_services: Option<&NSArray<CBService>>);

        #[cfg(all(
            feature = "CoreBluetooth_CBCharacteristic",
            feature = "Foundation_NSArray"
        ))]
        #[method_id(@__retain_semantics Other characteristics)]
        pub unsafe fn characteristics(&self) -> Option<Id<NSArray<CBCharacteristic>>>;

        #[cfg(all(
            feature = "CoreBluetooth_CBCharacteristic",
            feature = "Foundation_NSArray"
        ))]
        #[method(setCharacteristics:)]
        pub unsafe fn setCharacteristics(
            &self,
            characteristics: Option<&NSArray<CBCharacteristic>>,
        );

        #[cfg(feature = "CoreBluetooth_CBUUID")]
        #[method_id(@__retain_semantics Init initWithType:primary:)]
        pub unsafe fn initWithType_primary(
            this: Allocated<Self>,
            uuid: &CBUUID,
            is_primary: bool,
        ) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `CBAttribute`
    #[cfg(feature = "CoreBluetooth_CBMutableService")]
    unsafe impl CBMutableService {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBMutableService")]
    unsafe impl CBMutableService {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
