//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreBluetooth::*;
use crate::Foundation::*;

extern_static!(CBUUIDCharacteristicExtendedPropertiesString: &'static NSString);

extern_static!(CBUUIDCharacteristicUserDescriptionString: &'static NSString);

extern_static!(CBUUIDClientCharacteristicConfigurationString: &'static NSString);

extern_static!(CBUUIDServerCharacteristicConfigurationString: &'static NSString);

extern_static!(CBUUIDCharacteristicFormatString: &'static NSString);

extern_static!(CBUUIDCharacteristicAggregateFormatString: &'static NSString);

extern_static!(CBUUIDCharacteristicValidRangeString: &'static NSString);

extern_static!(CBUUIDL2CAPPSMCharacteristicString: &'static NSString);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CoreBluetooth_CBUUID")]
    pub struct CBUUID;

    #[cfg(feature = "CoreBluetooth_CBUUID")]
    unsafe impl ClassType for CBUUID {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "CoreBluetooth_CBUUID")]
unsafe impl NSCopying for CBUUID {}

#[cfg(feature = "CoreBluetooth_CBUUID")]
unsafe impl NSObjectProtocol for CBUUID {}

extern_methods!(
    #[cfg(feature = "CoreBluetooth_CBUUID")]
    unsafe impl CBUUID {
        #[cfg(feature = "Foundation_NSData")]
        #[method_id(@__retain_semantics Other data)]
        pub unsafe fn data(&self) -> Id<NSData>;

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other UUIDString)]
        pub unsafe fn UUIDString(&self) -> Id<NSString>;

        #[cfg(feature = "Foundation_NSString")]
        #[method_id(@__retain_semantics Other UUIDWithString:)]
        pub unsafe fn UUIDWithString(the_string: &NSString) -> Id<CBUUID>;

        #[cfg(feature = "Foundation_NSData")]
        #[method_id(@__retain_semantics Other UUIDWithData:)]
        pub unsafe fn UUIDWithData(the_data: &NSData) -> Id<CBUUID>;

        #[cfg(feature = "Foundation_NSUUID")]
        #[method_id(@__retain_semantics Other UUIDWithNSUUID:)]
        pub unsafe fn UUIDWithNSUUID(the_uuid: &NSUUID) -> Id<CBUUID>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CoreBluetooth_CBUUID")]
    unsafe impl CBUUID {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
